import '../../models/surah.dart';

const List<Surah> quranSurahs = [
  Surah(number: 1, name: "الفاتحة", englishName: "Al-Fatihah", englishNameTranslation: "Fâtiha", numberOfAyahs: 7, revelationType: "Meccan"),
  Surah(number: 2, name: "البقرة", englishName: "Al-Baqarah", englishNameTranslation: "Bakara", numberOfAyahs: 286, revelationType: "Medinan"),
  Surah(number: 3, name: "آل عمران", englishName: "Ali 'Imran", englishNameTranslation: "Âl-i İmrân", numberOfAyahs: 200, revelationType: "Medinan"),
  Surah(number: 4, name: "النساء", englishName: "An-Nisa", englishNameTranslation: "Nisâ", numberOfAyahs: 176, revelationType: "Medinan"),
  Surah(number: 5, name: "المائدة", englishName: "Al-Ma'idah", englishNameTranslation: "Mâide", numberOfAyahs: 120, revelationType: "Medinan"),
  Surah(number: 6, name: "الأنعام", englishName: "Al-An'am", englishNameTranslation: "En'âm", numberOfAyahs: 165, revelationType: "Meccan"),
  Surah(number: 7, name: "الأعراف", englishName: "Al-A'raf", englishNameTranslation: "A'râf", numberOfAyahs: 206, revelationType: "Meccan"),
  Surah(number: 8, name: "الأنفال", englishName: "Al-Anfal", englishNameTranslation: "Enfâl", numberOfAyahs: 75, revelationType: "Medinan"),
  Surah(number: 9, name: "التوبة", englishName: "At-Tawbah", englishNameTranslation: "Tevbe", numberOfAyahs: 129, revelationType: "Medinan"),
  Surah(number: 10, name: "يونس", englishName: "Yunus", englishNameTranslation: "Yûnus", numberOfAyahs: 109, revelationType: "Meccan"),
  Surah(number: 11, name: "هود", englishName: "Hud", englishNameTranslation: "Hûd", numberOfAyahs: 123, revelationType: "Meccan"),
  Surah(number: 12, name: "يوسف", englishName: "Yusuf", englishNameTranslation: "Yûsuf", numberOfAyahs: 111, revelationType: "Meccan"),
  Surah(number: 13, name: "الرعد", englishName: "Ar-Ra'd", englishNameTranslation: "Ra'd", numberOfAyahs: 43, revelationType: "Medinan"),
  Surah(number: 14, name: "إبراهيم", englishName: "Ibrahim", englishNameTranslation: "İbrâhîm", numberOfAyahs: 52, revelationType: "Meccan"),
  Surah(number: 15, name: "الحجر", englishName: "Al-Hijr", englishNameTranslation: "Hicr", numberOfAyahs: 99, revelationType: "Meccan"),
  Surah(number: 16, name: "النحل", englishName: "An-Nahl", englishNameTranslation: "Nahl", numberOfAyahs: 128, revelationType: "Meccan"),
  Surah(number: 17, name: "الإسراء", englishName: "Al-Isra", englishNameTranslation: "İsrâ", numberOfAyahs: 111, revelationType: "Meccan"),
  Surah(number: 18, name: "الكهف", englishName: "Al-Kahf", englishNameTranslation: "Kehf", numberOfAyahs: 110, revelationType: "Meccan"),
  Surah(number: 19, name: "مريم", englishName: "Maryam", englishNameTranslation: "Meryem", numberOfAyahs: 98, revelationType: "Meccan"),
  Surah(number: 20, name: "طه", englishName: "Taha", englishNameTranslation: "Tâhâ", numberOfAyahs: 135, revelationType: "Meccan"),
  Surah(number: 21, name: "الأنبياء", englishName: "Al-Anbiya", englishNameTranslation: "Enbiyâ", numberOfAyahs: 112, revelationType: "Meccan"),
  Surah(number: 22, name: "الحج", englishName: "Al-Hajj", englishNameTranslation: "Hac", numberOfAyahs: 78, revelationType: "Medinan"),
  Surah(number: 23, name: "المؤمنون", englishName: "Al-Mu'minun", englishNameTranslation: "Mü'minûn", numberOfAyahs: 118, revelationType: "Meccan"),
  Surah(number: 24, name: "النور", englishName: "An-Nur", englishNameTranslation: "Nûr", numberOfAyahs: 64, revelationType: "Medinan"),
  Surah(number: 25, name: "الفرقان", englishName: "Al-Furqan", englishNameTranslation: "Furkân", numberOfAyahs: 77, revelationType: "Meccan"),
  Surah(number: 26, name: "الشعراء", englishName: "Ash-Shu'ara", englishNameTranslation: "Şuarâ", numberOfAyahs: 227, revelationType: "Meccan"),
  Surah(number: 27, name: "النمل", englishName: "An-Naml", englishNameTranslation: "Neml", numberOfAyahs: 93, revelationType: "Meccan"),
  Surah(number: 28, name: "القصص", englishName: "Al-Qasas", englishNameTranslation: "Kasas", numberOfAyahs: 88, revelationType: "Meccan"),
  Surah(number: 29, name: "العنكبوت", englishName: "Al-'Ankabut", englishNameTranslation: "Ankebût", numberOfAyahs: 69, revelationType: "Meccan"),
  Surah(number: 30, name: "الروم", englishName: "Ar-Rum", englishNameTranslation: "Rûm", numberOfAyahs: 60, revelationType: "Meccan"),
  Surah(number: 31, name: "لقمان", englishName: "Luqman", englishNameTranslation: "Lokmân", numberOfAyahs: 34, revelationType: "Meccan"),
  Surah(number: 32, name: "السجدة", englishName: "As-Sajdah", englishNameTranslation: "Secde", numberOfAyahs: 30, revelationType: "Meccan"),
  Surah(number: 33, name: "الأحزاب", englishName: "Al-Ahzab", englishNameTranslation: "Ahzâb", numberOfAyahs: 73, revelationType: "Medinan"),
  Surah(number: 34, name: "سبأ", englishName: "Saba", englishNameTranslation: "Sebe'", numberOfAyahs: 54, revelationType: "Meccan"),
  Surah(number: 35, name: "فاطر", englishName: "Fatir", englishNameTranslation: "Fâtır", numberOfAyahs: 45, revelationType: "Meccan"),
  Surah(number: 36, name: "يس", englishName: "Ya-Sin", englishNameTranslation: "Yâsîn", numberOfAyahs: 83, revelationType: "Meccan"),
  Surah(number: 37, name: "الصافات", englishName: "As-Saffat", englishNameTranslation: "Sâffât", numberOfAyahs: 182, revelationType: "Meccan"),
  Surah(number: 38, name: "ص", englishName: "Sad", englishNameTranslation: "Sâd", numberOfAyahs: 88, revelationType: "Meccan"),
  Surah(number: 39, name: "الزمر", englishName: "Az-Zumar", englishNameTranslation: "Zümer", numberOfAyahs: 75, revelationType: "Meccan"),
  Surah(number: 40, name: "غافر", englishName: "Ghafir", englishNameTranslation: "Mü'min (Gâfir)", numberOfAyahs: 85, revelationType: "Meccan"),
  Surah(number: 41, name: "فصلت", englishName: "Fussilat", englishNameTranslation: "Fussılet", numberOfAyahs: 54, revelationType: "Meccan"),
  Surah(number: 42, name: "الشورى", englishName: "Ash-Shura", englishNameTranslation: "Şûrâ", numberOfAyahs: 53, revelationType: "Meccan"),
  Surah(number: 43, name: "الزخرف", englishName: "Az-Zukhruf", englishNameTranslation: "Zuhruf", numberOfAyahs: 89, revelationType: "Meccan"),
  Surah(number: 44, name: "الدخان", englishName: "Ad-Dukhan", englishNameTranslation: "Duhân", numberOfAyahs: 59, revelationType: "Meccan"),
  Surah(number: 45, name: "الجاثية", englishName: "Al-Jathiyah", englishNameTranslation: "Câsiye", numberOfAyahs: 37, revelationType: "Meccan"),
  Surah(number: 46, name: "الأحقاف", englishName: "Al-Ahqaf", englishNameTranslation: "Ahkâf", numberOfAyahs: 35, revelationType: "Meccan"),
  Surah(number: 47, name: "محمد", englishName: "Muhammad", englishNameTranslation: "Muhammed", numberOfAyahs: 38, revelationType: "Medinan"),
  Surah(number: 48, name: "الفتح", englishName: "Al-Fath", englishNameTranslation: "Fetih", numberOfAyahs: 29, revelationType: "Medinan"),
  Surah(number: 49, name: "الحجرات", englishName: "Al-Hujurat", englishNameTranslation: "Hucurât", numberOfAyahs: 18, revelationType: "Medinan"),
  Surah(number: 50, name: "ق", englishName: "Qaf", englishNameTranslation: "Kâf", numberOfAyahs: 45, revelationType: "Meccan"),
  Surah(number: 51, name: "الذاريات", englishName: "Adh-Dhariyat", englishNameTranslation: "Zâriyât", numberOfAyahs: 60, revelationType: "Meccan"),
  Surah(number: 52, name: "الطور", englishName: "At-Tur", englishNameTranslation: "Tûr", numberOfAyahs: 49, revelationType: "Meccan"),
  Surah(number: 53, name: "النجم", englishName: "An-Najm", englishNameTranslation: "Necm", numberOfAyahs: 62, revelationType: "Meccan"),
  Surah(number: 54, name: "القمر", englishName: "Al-Qamar", englishNameTranslation: "Kamer", numberOfAyahs: 55, revelationType: "Meccan"),
  Surah(number: 55, name: "الرحمن", englishName: "Ar-Rahman", englishNameTranslation: "Rahmân", numberOfAyahs: 78, revelationType: "Medinan"),
  Surah(number: 56, name: "الواقعة", englishName: "Al-Waqi'ah", englishNameTranslation: "Vâkıa", numberOfAyahs: 96, revelationType: "Meccan"),
  Surah(number: 57, name: "الحديد", englishName: "Al-Hadid", englishNameTranslation: "Hadîd", numberOfAyahs: 29, revelationType: "Medinan"),
  Surah(number: 58, name: "المجادلة", englishName: "Al-Mujadilah", englishNameTranslation: "Mücâdele", numberOfAyahs: 22, revelationType: "Medinan"),
  Surah(number: 59, name: "الحشر", englishName: "Al-Hashr", englishNameTranslation: "Haşr", numberOfAyahs: 24, revelationType: "Medinan"),
  Surah(number: 60, name: "الممتحنة", englishName: "Al-Mumtahanah", englishNameTranslation: "Mümtehine", numberOfAyahs: 13, revelationType: "Medinan"),
  Surah(number: 61, name: "الصف", englishName: "As-Saff", englishNameTranslation: "Saff", numberOfAyahs: 14, revelationType: "Medinan"),
  Surah(number: 62, name: "الجمعة", englishName: "Al-Jumu'ah", englishNameTranslation: "Cuma", numberOfAyahs: 11, revelationType: "Medinan"),
  Surah(number: 63, name: "المنافقون", englishName: "Al-Munafiqun", englishNameTranslation: "Münâfikûn", numberOfAyahs: 11, revelationType: "Medinan"),
  Surah(number: 64, name: "التغابن", englishName: "At-Taghabun", englishNameTranslation: "Teğâbun", numberOfAyahs: 18, revelationType: "Medinan"),
  Surah(number: 65, name: "الطلاق", englishName: "At-Talaq", englishNameTranslation: "Talâk", numberOfAyahs: 12, revelationType: "Medinan"),
  Surah(number: 66, name: "التحريم", englishName: "At-Tahrim", englishNameTranslation: "Tahrîm", numberOfAyahs: 12, revelationType: "Medinan"),
  Surah(number: 67, name: "الملك", englishName: "Al-Mulk", englishNameTranslation: "Mülk (Tebâreke)", numberOfAyahs: 30, revelationType: "Meccan"),
  Surah(number: 68, name: "القلم", englishName: "Al-Qalam", englishNameTranslation: "Kalem", numberOfAyahs: 52, revelationType: "Meccan"),
  Surah(number: 69, name: "الحاقة", englishName: "Al-Haqqah", englishNameTranslation: "Hâkka", numberOfAyahs: 52, revelationType: "Meccan"),
  Surah(number: 70, name: "المعارج", englishName: "Al-Ma'arij", englishNameTranslation: "Meâric", numberOfAyahs: 44, revelationType: "Meccan"),
  Surah(number: 71, name: "نوح", englishName: "Nuh", englishNameTranslation: "Nûh", numberOfAyahs: 28, revelationType: "Meccan"),
  Surah(number: 72, name: "الجن", englishName: "Al-Jinn", englishNameTranslation: "Cin", numberOfAyahs: 28, revelationType: "Meccan"),
  Surah(number: 73, name: "المزمل", englishName: "Al-Muzzammil", englishNameTranslation: "Müzzemmil", numberOfAyahs: 20, revelationType: "Meccan"),
  Surah(number: 74, name: "المدثر", englishName: "Al-Muddaththir", englishNameTranslation: "Müddessir", numberOfAyahs: 56, revelationType: "Meccan"),
  Surah(number: 75, name: "القيامة", englishName: "Al-Qiyamah", englishNameTranslation: "Kıyâme", numberOfAyahs: 40, revelationType: "Meccan"),
  Surah(number: 76, name: "الانسان", englishName: "Al-Insan", englishNameTranslation: "İnsân (Dehr)", numberOfAyahs: 31, revelationType: "Medinan"),
  Surah(number: 77, name: "المرسلات", englishName: "Al-Mursalat", englishNameTranslation: "Mürselât", numberOfAyahs: 50, revelationType: "Meccan"),
  Surah(number: 78, name: "النبأ", englishName: "An-Naba", englishNameTranslation: "Nebe (Amme)", numberOfAyahs: 40, revelationType: "Meccan"),
  Surah(number: 79, name: "النازعات", englishName: "An-Nazi'at", englishNameTranslation: "Nâziât", numberOfAyahs: 46, revelationType: "Meccan"),
  Surah(number: 80, name: "عبس", englishName: "'Abasa", englishNameTranslation: "Abese", numberOfAyahs: 42, revelationType: "Meccan"),
  Surah(number: 81, name: "التكوير", englishName: "At-Takwir", englishNameTranslation: "Tekvîr", numberOfAyahs: 29, revelationType: "Meccan"),
  Surah(number: 82, name: "الانفطار", englishName: "Al-Infitar", englishNameTranslation: "İnfitâr", numberOfAyahs: 19, revelationType: "Meccan"),
  Surah(number: 83, name: "المطففين", englishName: "Al-Mutaffifin", englishNameTranslation: "Mutaffifîn", numberOfAyahs: 36, revelationType: "Meccan"),
  Surah(number: 84, name: "الانشقاق", englishName: "Al-Inshiqaq", englishNameTranslation: "İnşikâk", numberOfAyahs: 25, revelationType: "Meccan"),
  Surah(number: 85, name: "البروج", englishName: "Al-Buruj", englishNameTranslation: "Burûc", numberOfAyahs: 22, revelationType: "Meccan"),
  Surah(number: 86, name: "الطارق", englishName: "At-Tariq", englishNameTranslation: "Târık", numberOfAyahs: 17, revelationType: "Meccan"),
  Surah(number: 87, name: "الأعلى", englishName: "Al-A'la", englishNameTranslation: "A'lâ", numberOfAyahs: 19, revelationType: "Meccan"),
  Surah(number: 88, name: "الغاشية", englishName: "Al-Ghashiyah", englishNameTranslation: "Gâşiye", numberOfAyahs: 26, revelationType: "Meccan"),
  Surah(number: 89, name: "الفجر", englishName: "Al-Fajr", englishNameTranslation: "Fecr", numberOfAyahs: 30, revelationType: "Meccan"),
  Surah(number: 90, name: "البلد", englishName: "Al-Balad", englishNameTranslation: "Beled", numberOfAyahs: 20, revelationType: "Meccan"),
  Surah(number: 91, name: "الشمس", englishName: "Ash-Shams", englishNameTranslation: "Şems", numberOfAyahs: 15, revelationType: "Meccan"),
  Surah(number: 92, name: "الليل", englishName: "Al-Layl", englishNameTranslation: "Leyl", numberOfAyahs: 21, revelationType: "Meccan"),
  Surah(number: 93, name: "الضحى", englishName: "Ad-Duha", englishNameTranslation: "Duhâ", numberOfAyahs: 11, revelationType: "Meccan"),
  Surah(number: 94, name: "الشرح", englishName: "Al-Inshirah", englishNameTranslation: "İnşirâh (Şerh)", numberOfAyahs: 8, revelationType: "Meccan"),
  Surah(number: 95, name: "التين", englishName: "At-Tin", englishNameTranslation: "Tîn", numberOfAyahs: 8, revelationType: "Meccan"),
  Surah(number: 96, name: "العلق", englishName: "Al-'Alaq", englishNameTranslation: "Alak", numberOfAyahs: 19, revelationType: "Meccan"),
  Surah(number: 97, name: "القدر", englishName: "Al-Qadr", englishNameTranslation: "Kadir", numberOfAyahs: 5, revelationType: "Meccan"),
  Surah(number: 98, name: "البينة", englishName: "Al-Bayyinah", englishNameTranslation: "Beyyine", numberOfAyahs: 8, revelationType: "Medinan"),
  Surah(number: 99, name: "الزلزلة", englishName: "Az-Zalzalah", englishNameTranslation: "Zilzâl", numberOfAyahs: 8, revelationType: "Medinan"),
  Surah(number: 100, name: "العاديات", englishName: "Al-'Adiyat", englishNameTranslation: "Âdiyât", numberOfAyahs: 11, revelationType: "Meccan"),
  Surah(number: 101, name: "القارعة", englishName: "Al-Qari'ah", englishNameTranslation: "Kâria", numberOfAyahs: 11, revelationType: "Meccan"),
  Surah(number: 102, name: "التكاثر", englishName: "At-Takathur", englishNameTranslation: "Tekâsür", numberOfAyahs: 8, revelationType: "Meccan"),
  Surah(number: 103, name: "العصر", englishName: "Al-'Asr", englishNameTranslation: "Asr", numberOfAyahs: 3, revelationType: "Meccan"),
  Surah(number: 104, name: "الهمزة", englishName: "Al-Humazah", englishNameTranslation: "Hümeze", numberOfAyahs: 9, revelationType: "Meccan"),
  Surah(number: 105, name: "الفيل", englishName: "Al-Fil", englishNameTranslation: "Fîl", numberOfAyahs: 5, revelationType: "Meccan"),
  Surah(number: 106, name: "قريش", englishName: "Quraysh", englishNameTranslation: "Kureyş", numberOfAyahs: 4, revelationType: "Meccan"),
  Surah(number: 107, name: "الماعون", englishName: "Al-Ma'un", englishNameTranslation: "Mâûn", numberOfAyahs: 7, revelationType: "Meccan"),
  Surah(number: 108, name: "الكوثر", englishName: "Al-Kawthar", englishNameTranslation: "Kevser", numberOfAyahs: 3, revelationType: "Meccan"),
  Surah(number: 109, name: "الكافرون", englishName: "Al-Kafirun", englishNameTranslation: "Kâfirûn", numberOfAyahs: 6, revelationType: "Meccan"),
  Surah(number: 110, name: "النصر", englishName: "An-Nasr", englishNameTranslation: "Nasr", numberOfAyahs: 3, revelationType: "Medinan"),
  Surah(number: 111, name: "المسد", englishName: "Al-Masad", englishNameTranslation: "Mesed (Tebbet)", numberOfAyahs: 5, revelationType: "Meccan"),
  Surah(number: 112, name: "الإخلاص", englishName: "Al-Ikhlas", englishNameTranslation: "İhlâs", numberOfAyahs: 4, revelationType: "Meccan"),
  Surah(number: 113, name: "الفلق", englishName: "Al-Falaq", englishNameTranslation: "Felak", numberOfAyahs: 5, revelationType: "Meccan"),
  Surah(number: 114, name: "الناس", englishName: "An-Nas", englishNameTranslation: "Nâs", numberOfAyahs: 6, revelationType: "Meccan"),
];
